import { createContext, useState, type ReactNode } from 'react';

export interface LanguageContextType {
    language: 'en' | 'zh';
    t: (key: string) => string;
    setLanguage: (lang: 'en' | 'zh') => void;
}

const translations = {
    en: {
        // Global
        'global.tagline': 'Dedicated to Chinese patients, connecting with top hospitals across the United States, providing you with reliable medical services in the USA',

        // Navigation
        'nav.home': 'Home',
        'nav.about': 'About',
        'nav.services': 'Services',
        'nav.procedures': 'Procedures',
        'nav.story': 'Our Story',
        'nav.letter': 'A Letter to You',
        'nav.contact': 'Contact',
        'nav.appointment': 'Book Appointment',

        // Home Page
        'home.title': 'Welcome to HealUSA Medical Assistance',
        'home.subtitle': 'Professional medical services for Chinese patients seeking healthcare in the United States',
        'home.features': 'Why Choose Us?',
        'home.feature1': 'Expert Doctors',
        'home.feature1_desc': 'Board-certified physicians with 15+ years of experience',
        'home.feature2': 'Advanced Technology',
        'home.feature2_desc': 'State-of-the-art medical equipment and facilities',
        'home.feature3': 'Multilingual Support',
        'home.feature3_desc': 'Fluent Chinese and English support throughout your journey',
        'home.feature4': 'Affordable Costs',
        'home.feature4_desc': 'Competitive pricing with transparent billing',
        'home.cta_title': 'Ready to Book Your Appointment?',
        'home.cta_subtitle': 'Schedule a consultation with our medical team today',

        // About Page
        'about.title': 'About HealUSA',
        'about.subtitle': 'Dedicated to providing excellent medical care to international patients',
        'about.mission': 'Our Mission',
        'about.mission_desc': 'To provide accessible, high-quality medical services to Chinese patients seeking treatment in the United States. We believe in making healthcare affordable and stress-free through personalized care and comprehensive support.',
        'about.team': 'Our Team',
        'about.medical_director': 'Medical Director',
        'about.coordinator': 'Patient Coordinator',
        'about.translator': 'Medical Translator',
        'about.team_desc1': '15+ years of surgical experience, specializing in orthopedic procedures',
        'about.team_desc2': '10+ years managing international patient care and logistics',
        'about.team_desc3': '12+ years of medical translation and patient communication',
        'about.experience': 'Our Experience',
        'about.patients': 'Patients Treated',
        'about.years': 'Years in Business',
        'about.procedures': 'Procedures Offered',
        'about.satisfaction': 'Patient Satisfaction',
        'about.why_choose': 'Why Choose HealUSA?',
        'about.reason1': 'Accredited hospitals and certified surgeons',
        'about.reason2': 'Complete translation and interpretation services',
        'about.reason3': 'Assistance with visa and travel arrangements',
        'about.reason4': 'Post-operative care and follow-up support',

        // Services Page
        'services.title': 'Our Medical Services',
        'services.subtitle': 'Comprehensive healthcare solutions tailored to your needs',
        'services.dental': 'Dental Services',
        'services.dental_desc': 'Complete dental care including cosmetic and restorative procedures',
        'services.vision': 'Vision Care',
        'services.vision_desc': 'Advanced eye surgery and vision correction procedures',
        'services.orthopedic': 'Orthopedic Surgery',
        'services.orthopedic_desc': 'Joint replacement and orthopedic procedures',
        'services.cardiology': 'Cardiology',
        'services.cardiology_desc': 'Heart and cardiovascular disease treatment',
        'services.neurology': 'Neurology',
        'services.neurology_desc': 'Brain and nervous system procedures',
        'services.reproductive': 'Reproductive Health',
        'services.reproductive_desc': 'Fertility, obstetric, and gynecological services',
        'services.process': 'Our Process',
        'services.step1': 'Consultation',
        'services.step1_desc': 'Free initial consultation to assess your needs',
        'services.step2': 'Planning',
        'services.step2_desc': 'Personalized treatment plan creation',
        'services.step3': 'Procedure',
        'services.step3_desc': 'Professional medical care at accredited hospitals',
        'services.step4': 'Follow-up',
        'services.step4_desc': 'Comprehensive post-operative care',

        // Procedures Page
        'procedures.title': 'Procedure Catalog',
        'procedures.subtitle': 'Browse our comprehensive list of available medical procedures',
        'procedures.all': 'All Categories',
        'procedures.dental': 'Dental',
        'procedures.vision': 'Vision',
        'procedures.orthopedic': 'Orthopedic',
        'procedures.cardiology': 'Cardiology',
        'procedures.reproductive': 'Reproductive',
        'procedures.search_placeholder': 'Search procedures...',
        'procedures.filter': 'Filter by Category',
        'procedures.showing': 'Showing',
        'procedures.results': 'results',
        'procedures.price': 'Price Range',
        'procedures.duration': 'Duration',
        'procedures.inquiry': 'Send Inquiry',
        'procedures.no_results': 'No procedures found. Try adjusting your search.',

        // Contact Page
        'contact.title': 'Get In Touch',
        'contact.subtitle': 'Have questions? We\'re here to help!',
        'contact.address': 'Address',
        'contact.phone': 'Phone',
        'contact.email': 'Email',
        'contact.hours': 'Business Hours',
        'contact.name': 'Full Name',
        'contact.name_placeholder': 'Your full name',
        'contact.email_address': 'Email Address',
        'contact.email_placeholder': 'your@email.com',
        'contact.wechat': 'WeChat ID',
        'contact.wechat_placeholder': 'Your WeChat ID',
        'contact.phone_number': 'Phone Number',
        'contact.phone_placeholder': '+1 (XXX) XXX-XXXX',
        'contact.subject': 'Subject',
        'contact.subject_placeholder': 'How can we help?',
        'contact.message': 'Message',
        'contact.message_placeholder': 'Please provide details...',
        'contact.send': 'Send Message',
        'contact.success': 'Thank you! We\'ll get back to you soon.',

        // Appointment Page
        'appointment.title': 'Book Your Appointment',
        'appointment.subtitle': 'Schedule a consultation with our medical team',
        'appointment.name': 'Full Name',
        'appointment.name_placeholder': 'Your full name',
        'appointment.email': 'Email Address',
        'appointment.email_placeholder': 'your@email.com',
        'appointment.wechat': 'WeChat ID',
        'appointment.wechat_placeholder': 'Your WeChat ID',
        'appointment.phone': 'Phone Number',
        'appointment.phone_placeholder': '+1 (XXX) XXX-XXXX',
        'appointment.procedure': 'Procedure of Interest',
        'appointment.select_procedure': 'Select a procedure',
        'appointment.date': 'Preferred Date',
        'appointment.time': 'Preferred Time',
        'appointment.select_time': 'Select a time',
        'appointment.notes': 'Additional Notes',
        'appointment.notes_placeholder': 'Any medical history or special requests...',
        'appointment.book': 'Book Appointment',
        'appointment.success': 'Your appointment request has been submitted! We\'ll confirm shortly.',
        'appointment.info': 'Need Help?',
        'appointment.info_text': 'Our patient coordinators are available to assist with scheduling. Contact us at info@healusa.com or call +1 (212) 555-0123.',

        // Not Found Page
        'notfound.title': 'Page Not Found',
        'notfound.message': 'Sorry, the page you\'re looking for doesn\'t exist.',
        'notfound.back_home': 'Back to Home',

        // Story Page
        'story.title': 'I Want to Tell You: Our Family\'s Five-Year Journey of Medical Treatment in the USA',
        'story.subtitle': 'The True Story of Glory, Founder of USA Medical Travel',
        'story.intro1': 'My name is Glory.',
        'story.intro2': 'Many people ask me: Why do you do "USA medical travel"? The answer is simple: because I walked that most difficult path myself.',
        'story.intro3': 'I write this to share our real experience with future patients who may embark on the same journey, and to record our family\'s unforgettable journey of fighting cancer in America—filled with hope and dignity.',

        'story.section1_title': 'I. That Year, When Fate Suddenly Changed',
        'story.section1_p1': 'In December 2015, my wife Wang Yuanyuan was diagnosed with breast cancer. She was only in her thirties, our child was young, and our life was full of plans.',
        'story.section1_p2': 'We went to the best Grade A tertiary hospitals in China, found the chief physician of the breast department at Jiangsu Provincial People\'s Hospital, a renowned expert in the field.',
        'story.section1_p3': 'She underwent chemotherapy, radiotherapy, surgery, and endocrine therapy—everything went according to procedure. We thought the storm had passed.',
        'story.section1_p4': 'However, three years later, fate tested us again. In December 2018, she was diagnosed with a recurrence.',
        'story.section1_p5': 'In fact, she had symptoms as early as that summer, but the doctor was overconfident, saying: "It\'s fine, I also get short of breath." That one sentence made us miss the golden window for treatment.',
        'story.section1_p6': 'At that moment I deeply realized—Chinese doctors do their best, but the system isn\'t complete enough: Patients must register themselves, run tests themselves, collect reports themselves, and monitor the process themselves.',
        'story.section1_p7': 'My wife also said later: "The scariest thing about illness isn\'t the disease itself, but the delays."',

        'story.section2_title': 'II. That Night, I Decided to Take Her to America',
        'story.section2_p1': 'That night, we didn\'t go home—we couldn\'t face our child and elderly parents. We stayed in a small hotel near the hospital, unable to sleep all night.',
        'story.section2_p2': 'I asked the attending physician: "Is there still hope in China?" He was silent for a moment, then said: "There\'s one more drug, average survival is about 22 months. If you have the means, go to America—the drugs are updated faster there, and the treatment philosophy is more advanced."',
        'story.section2_p3': 'I made the decision immediately: No matter the cost, I would take her to America.',
        'story.section2_p4': 'That night, I didn\'t close my eyes. The next morning, I booked plane tickets.',
        'story.section2_p5': 'I told her: "We\'re going to America, there must still be hope." She nodded. We knew this would change our entire family\'s destiny.',
        'story.section2_p6': 'On the flight, the flight attendant arranged a whole row of seats for her. She rested against me as I looked out the window at the clouds, with only one thought: As long as she can live longer than 22 months, every decision is worth it.',

        'story.section3_title': 'III. In America: The First Time Feeling True Tenderness and Respect',
        'story.section3_p1': 'After arriving in America, from outpatient to inpatient care, from doctors and nurses to medical translators and volunteers, everyone was so considerate and gentle.',
        'story.section3_p2': 'This kind of "meticulous care" truly gives patients and families strength.',
        'story.section3_p3': 'The hospital was clean, quiet, comfortable like home; every process was clear and transparent, with no passing the buck, no chaos.',
        'story.section3_p4': 'What I\'ll never forget is our attending physician, Dr. Patel. Every time he saw us, he would smile and hug us, his eyes full of sincerity and compassion.',
        'story.section3_p5': 'At that moment I understood: In America, medical care isn\'t just about "treating disease"—it\'s about mutual support and trust between people.',

        'story.section4_title': 'IV. These Five Years: She Lived with Dignity, We Lived with Direction',
        'story.section4_p1': 'If we had stayed in China, perhaps the survival period would have been only 24 months; but in America, she walked through another five years, and regained her life\'s rhythm and dignity.',
        'story.section4_p2': 'During these five years, she accompanied our child growing up, participated in rehabilitation, learned English, and did things she loved. Our family ate together, chatted, watched movies—life became peaceful and powerful again.',
        'story.section4_p3': 'Of course, there were also emergency visits, treatment setbacks, anxiety, fear, and tears during those five years.',
        'story.section4_p4': 'But each time, we were supported by a professional medical team. They never let patients and families feel alone.',

        'story.section5_title': 'V. The World\'s Most Advanced Doctors, Medications, and Clinical Trials',
        'story.section5_p1': 'We went to oncology centers in Los Angeles, MD Anderson in Texas, Dana-Farber in Boston, and UCLA\'s top breast cancer team.',
        'story.section5_p2': 'My wife received 13 chemotherapy drugs, 4 radiation treatments, and participated in the latest CAR-T clinical trials.',
        'story.section5_p3': 'Doctors customized treatment plans based on her condition, focusing not only on efficacy but also on quality of life.',
        'story.section5_quote': '"You are a person, not a case number."',
        'story.section5_p4': 'What truly gave me peace of mind was America\'s medical insurance system. Many think American healthcare is expensive, but actually—as long as insurance is properly configured, American healthcare can be even more economical than China.',
        'story.section5_p5': 'I purchased legal commercial medical insurance applicable to foreigners:',
        'story.section5_list1': 'Although premiums weren\'t low, almost all treatment costs were covered',
        'story.section5_list2': 'I only paid fixed monthly premiums plus small copays',
        'story.section5_list3': 'She could use the world\'s newest, most advanced, and most expensive medications',
        'story.section5_p6': 'In China, many imported drugs are out-of-pocket; in America, as long as insurance approves, almost everything is covered.',
        'story.section5_p7': 'This is the power of the system.',

        'story.section6_title': 'VI. What Patients Worry About Most—We Can Help You Solve',
        'story.section6_p1': 'Many patients worry most about: "How does the process work?" "How do I get a visa?" "What if I don\'t speak the language?" "Can I afford American healthcare?"',
        'story.section6_p2': 'I\'ve experienced all of this, and I can help you solve it. We have a complete, mature process that can:',
        'story.service1_title': '📋 Visa Consultation and Preparation',
        'story.service1_desc': 'Help prepare medical invitation letters, medical documents, and choose the most suitable visa approach.',
        'story.service2_title': '🏥 Connect with American Hospitals and Doctors',
        'story.service2_desc': 'Directly contact American hospitals and provide official appointment confirmations.',
        'story.service3_title': '💰 Plan and Legally Purchase American Commercial Medical Insurance',
        'story.service3_desc': 'This step is most critical—it\'s the core of solving "expensive healthcare." Consult me, and I\'ll tell you how. I\'ll personally help you arrange insurance so you have no financial pressure for treatment in America.',
        'story.service4_title': '💵 Transparent, Controllable Costs',
        'story.service4_desc': 'Many patients\' actual expenses end up lower than self-paying in China.',
        'story.service5_title': '🤝 Full Support After Arrival',
        'story.service5_desc': 'Airport pickup, accommodation, translation, medical accompaniment, follow-up arrangements—we can arrange everything.',
        'story.section6_p3': 'You don\'t need to be afraid, and you don\'t need to figure it out yourself. You just need to take the first step, and we\'ll complete the rest.',

        'story.section7_title': 'VII. Why I Continue Doing This',
        'story.section7_p1': 'Those who\'ve experienced life and death understand the value of life better. I don\'t do this for money.',
        'story.section7_p2': 'I just feel that: if the path I\'ve walked can bring light to others, it\'s worthwhile.',
        'story.section7_p3': 'I believe in science, I believe in the system, I believe in love. Around me are volunteers willing to help patients contact hospitals, prepare materials, and answer questions for free.',
        'story.section7_p4': 'We hope to help more families take fewer detours, have less helplessness, and more confidence.',

        'story.section8_title': 'VIII. In Closing',
        'story.section8_p1': 'Five years have taught us to understand "life" and "hope" anew. My wife continues treatment in America, living with regularity, direction, and dignity. Our whole family has learned to cherish the peace and companionship of each day.',
        'story.section8_p2': 'I write this experience to tell all families going through pain:',
        'story.section8_highlight': 'There truly is hope in this world.',
        'story.section8_p3': 'If you\'re hesitating, afraid, wavering, please believe me: This path is worth taking.',
        'story.section8_p4': 'I\'m willing to share my personal experience with you, to help you walk more steadily, to have less fear and more confidence.',
        'story.signature_name': 'Glory Gao',
        'story.signature_title': 'Founder of USA Medical Travel',
        'story.signature_quote': '"Turning the path I\'ve walked into the light you can rely on."',

        // Letter Page
        'letter.title': 'A Letter to You',
        'letter.greeting': 'Dear Friend,',
        'letter.opening1': 'When you read this letter, perhaps you are going through a difficult moment in life. Perhaps you are anxiously searching for answers, or desperately seeking hope for your family.',
        'letter.opening2': 'Please allow me to first express my most sincere greetings. I understand how you feel right now—because I once stood in your position.',
        'letter.opening3': 'I am Glory Gao, the founder of this USA medical travel service. I am a husband, a father, and someone who accompanied my family through a five-year journey fighting cancer.',
        'letter.intro1': 'It was that experience that made me deeply understand:',
        'letter.intro2': '',
        'letter.intro3': '',
        'letter.highlight1': 'What people need most in despair is not complex procedures, but a steady hand, a sincere heart, and trustworthy guidance.',

        'letter.why_title': 'Why Am I Willing to Contact You Personally?',
        'letter.why1': 'Because I don\'t want you to take detours anymore.',
        'letter.why2': 'Because I know every decision relates to quality of life.',
        'letter.why3': 'Because I know that in the face of illness, "trust" is more important than any medical terminology.',
        'letter.why4': 'I\'ve walked that path. I know what to do at each step. I know when delays are most likely to happen. I know how to bring hope back.',
        'letter.why5': 'I want to use my real experience to let you feel that:',
        'letter.why6': 'I\'m not "providing a service"—I want to walk this path with you.',

        'letter.trust_title': 'Why Can You Trust Me?',
        'letter.trust_intro': 'Because I\'ve experienced everything you\'re going through:',
        'letter.trust1': 'I know what despair feels like',
        'letter.trust2': 'I know what fear feels like',
        'letter.trust3': 'I know the feeling of waiting for test results',
        'letter.trust4': 'I know the pressure every family bears',
        'letter.trust5': 'I know what a husband, a mother, a child needs most when ill',
        'letter.trust_because': 'Because of this, I understand better than anyone:',
        'letter.trust_emphasis': 'Healthcare isn\'t a cold process—it\'s a responsibility.',

        'letter.commitment1': 'To my wife, I give my all. To my family, I fulfill my duty. To patients, I will treat you with the same sincerity.',
        'letter.commitment2': 'I\'m willing to take on this heavy yet meaningful work because this is my life\'s new mission.',
        'letter.commitment3': 'This makes me feel real, valuable, and fulfilled.',
        'letter.commitment4': 'Because this work is "too heavy," there aren\'t many who can truly do it. But I\'m suitable, and I\'m willing.',

        'letter.promise_title': 'I Promise: I Will Personally Reply to Every Consultation',
        'letter.promise1': 'We are a very small team—only 5 core members, each one conscientious and caring.',
        'letter.promise2': 'After you arrive in America, we will also connect you with a local non-profit volunteer organization to help you settle in, accompany you to appointments, provide language support, and truly give you peace of mind.',
        'letter.promise3': 'But please understand: The number of people I can personally serve is limited.',
        'letter.promise4': 'So if you need help, please contact me as soon as possible. All consultations are free—as long as you\'re willing to reach out, I\'m here.',

        'letter.final_quote': 'Choose what I bear, bear what I choose.',
        'letter.final1': 'I will be responsible to the end for every patient, every family, every piece of advice, and every decision I give.',
        'letter.final2': 'I hope you can give me a chance to use my personal experience and professional expertise to help you walk more steadily, live with better quality, and make each day more dignified.',

        'letter.cta1': 'If you are hesitating, afraid, or don\'t know where to start—',
        'letter.cta2': 'Please contact me immediately. I will give you the most caring, sincere, and responsible response at the first opportunity.',

        'letter.signature_name': 'Founder: Glory Gao',
        'letter.signature_title': '',
        'letter.signature_message': 'This is my promise, and the reason I am willing to walk alongside you.',

        // Footer
        'footer.copyright': '© 2024 HealUSA. All rights reserved.',
    },
    zh: {
        // 全局
        'global.tagline': '专注华人患者，连接全美国顶级医院，为您提供可信赖的赴美就医服务',

        // 导航
        'nav.home': '首页',
        'nav.about': '关于我们',
        'nav.services': '服务',
        'nav.procedures': '医疗程序',
        'nav.story': '我们的故事',
        'nav.letter': '给你的一封信',
        'nav.contact': '联系我们',
        'nav.appointment': '预约',

        // 首页
        'home.title': '欢迎来到 HealUSA 医疗援助',
        'home.subtitle': '为寻求美国医疗服务的中国患者提供专业医疗服务',
        'home.features': '为什么选择我们?',
        'home.feature1': '专家医生',
        'home.feature1_desc': '拥有15年以上经验的认证医师',
        'home.feature2': '先进技术',
        'home.feature2_desc': '最先进的医疗设备和设施',
        'home.feature3': '多语言支持',
        'home.feature3_desc': '全程流利的中英文支持',
        'home.feature4': '经济实惠',
        'home.feature4_desc': '具有竞争力的价格和透明账单',
        'home.cta_title': '准备预约?',
        'home.cta_subtitle': '立即与我们的医疗团队安排咨询',

        // 关于页面
        'about.title': '关于 HealUSA',
        'about.subtitle': '致力于为寻求美国治疗的中国患者提供优质医疗服务',
        'about.mission': '我们的使命',
        'about.mission_desc': '为寻求美国治疗的中国患者提供可获得、高质量的医疗服务。我们通过个性化护理和全面支持，让医疗保健变得经济实惠且无忧。',
        'about.team': '我们的团队',
        'about.medical_director': '医疗主任',
        'about.coordinator': '患者协调员',
        'about.translator': '医学翻译',
        'about.team_desc1': '15年以上手术经验，专门从事骨科手术',
        'about.team_desc2': '10年以上国际患者护理和物流管理经验',
        'about.team_desc3': '12年以上医学翻译和患者沟通经验',
        'about.experience': '我们的经验',
        'about.patients': '接受治疗的患者',
        'about.years': '年运营',
        'about.procedures': '提供的程序',
        'about.satisfaction': '患者满意度',
        'about.why_choose': '为什么选择 HealUSA?',
        'about.reason1': '认证医院和认证外科医生',
        'about.reason2': '完整的翻译和口译服务',
        'about.reason3': '协助签证和旅行安排',
        'about.reason4': '术后护理和跟进支持',

        // 服务页面
        'services.title': '我们的医疗服务',
        'services.subtitle': '根据您的需求定制的综合医疗保健解决方案',
        'services.dental': '牙科服务',
        'services.dental_desc': '包括美容和修复程序的完整牙科护理',
        'services.vision': '视力护理',
        'services.vision_desc': '先进的眼科手术和视力矫正程序',
        'services.orthopedic': '骨科手术',
        'services.orthopedic_desc': '关节置换和骨科手术',
        'services.cardiology': '心脏病学',
        'services.cardiology_desc': '心脏和心血管疾病治疗',
        'services.neurology': '神经学',
        'services.neurology_desc': '脑和神经系统手术',
        'services.reproductive': '生殖健康',
        'services.reproductive_desc': '生育、产科和妇科服务',
        'services.process': '我们的流程',
        'services.step1': '咨询',
        'services.step1_desc': '免费初步咨询评估您的需求',
        'services.step2': '计划',
        'services.step2_desc': '制定个性化治疗计划',
        'services.step3': '程序',
        'services.step3_desc': '在认证医院提供专业医疗护理',
        'services.step4': '跟进',
        'services.step4_desc': '全面的术后护理',

        // 医疗程序页面
        'procedures.title': '医疗程序目录',
        'procedures.subtitle': '浏览我们的综合可用医疗程序列表',
        'procedures.all': '所有类别',
        'procedures.dental': '牙科',
        'procedures.vision': '视力',
        'procedures.orthopedic': '骨科',
        'procedures.cardiology': '心脏病学',
        'procedures.reproductive': '生殖',
        'procedures.search_placeholder': '搜索程序...',
        'procedures.filter': '按类别筛选',
        'procedures.showing': '显示',
        'procedures.results': '结果',
        'procedures.price': '价格范围',
        'procedures.duration': '持续时间',
        'procedures.inquiry': '发送咨询',
        'procedures.no_results': '未找到程序。尝试调整您的搜索。',

        // 联系页面
        'contact.title': '联系我们',
        'contact.subtitle': '有问题？我们很乐意帮助！',
        'contact.address': '地址',
        'contact.phone': '电话',
        'contact.email': '电子邮件',
        'contact.hours': '营业时间',
        'contact.name': '全名',
        'contact.name_placeholder': '您的全名',
        'contact.email_address': '电子邮件地址',
        'contact.email_placeholder': 'your@email.com',
        'contact.wechat': '微信号',
        'contact.wechat_placeholder': '请输入您的微信号',
        'contact.phone_number': '电话号码',
        'contact.phone_placeholder': '+1 (XXX) XXX-XXXX',
        'contact.subject': '主题',
        'contact.subject_placeholder': '我们可以如何帮助？',
        'contact.message': '消息',
        'contact.message_placeholder': '请提供详细信息...',
        'contact.send': '发送消息',
        'contact.success': '感谢！我们会尽快与您联系。',

        // 预约页面
        'appointment.title': '预约',
        'appointment.subtitle': '与我们的医疗团队安排咨询',
        'appointment.name': '全名',
        'appointment.name_placeholder': '您的全名',
        'appointment.email': '电子邮件地址',
        'appointment.email_placeholder': 'your@email.com',
        'appointment.wechat': '微信号',
        'appointment.wechat_placeholder': '请输入您的微信号',
        'appointment.phone': '电话号码',
        'appointment.phone_placeholder': '+1 (XXX) XXX-XXXX',
        'appointment.procedure': '感兴趣的程序',
        'appointment.select_procedure': '选择程序',
        'appointment.date': '首选日期',
        'appointment.time': '首选时间',
        'appointment.select_time': '选择时间',
        'appointment.notes': '其他备注',
        'appointment.notes_placeholder': '任何病历或特殊要求...',
        'appointment.book': '预约',
        'appointment.success': '您的预约请求已提交！我们会尽快确认。',
        'appointment.info': '需要帮助？',
        'appointment.info_text': '我们的患者协调员可以协助安排。请通过 info@healusa.com 或 +1 (212) 555-0123 与我们联系。',

        // 未找到页面
        'notfound.title': '页面未找到',
        'notfound.message': '抱歉，您查找的页面不存在。',
        'notfound.back_home': '返回首页',

        // 故事页面
        'story.title': '我想告诉你：我们这一家，在美国治病的这五年',
        'story.subtitle': '赴美医疗 · 创始人 Glory 的真实故事',
        'story.intro1': '我叫 Glory。',
        'story.intro2': '很多人问我：为什么要做"赴美医疗"这件事？答案很简单：因为我自己走过那条最难的路。',
        'story.intro3': '我写下这些，是想把我们真实的经历分享给未来可能踏上同样旅程的病友们，也记录下我们一家难忘的、充满希望和尊严的美国抗癌之路。',

        'story.section1_title': '一、那一年，命运忽然改变',
        'story.section1_p1': '2015 年 12 月，我太太 王媛媛 确诊乳腺癌。她才三十多岁，孩子还小，我们的生活原本充满计划。',
        'story.section1_p2': '我们去了国内最好的三甲医院，找到了江苏省人民医院乳腺科的主任医师，也是行业非常知名的专家。',
        'story.section1_p3': '她接受了化疗、放疗、手术和内分泌治疗，一切都按流程进行。我们以为风雨已经过去。',
        'story.section1_p4': '然而三年后，命运再次试探我们。2018 年 12 月，她被确诊复发。',
        'story.section1_p5': '其实早在那年夏天她就出现不适，但医生过于自信，说："没事，我也会喘，"这一句话，让我们错过了黄金治疗窗口。',
        'story.section1_p6': '我那时深刻意识到——中国医生尽心尽力，但体系不够完善：病人要自己挂号、自己跑检查、自己取报告、自己盯流程。',
        'story.section1_p7': '我太太后来也说："得病最怕的不是病，而是耽误。"',

        'story.section2_title': '二、那一夜，我决定带她去美国',
        'story.section2_p1': '那天晚上，我们没有回家，不敢面对孩子和老人。我们住在医院附近的小酒店里，一夜无眠。',
        'story.section2_p2': '我问主治医生："在国内还有希望吗？"他沉默片刻，说："还有一种药，平均生存期大约 22 个月。如果有条件，去美国吧，那里的药物更新得更快，治疗理念也更先进。"',
        'story.section2_p3': '我当机立断：无论代价多大，都要带她去美国。',
        'story.section2_p4': '那一夜，我整晚没合眼。第二天清晨我就订好了机票。',
        'story.section2_p5': '我对她说："我们去美国，一定还有希望。"她点点头。我们知道这会改变我们全家的命运。',
        'story.section2_p6': '在航班上，空姐为她安排了一整排座位。她靠着我休息，我看着窗外的云，心里只有一个念头：只要她能比 22 个月多活，所有决定都是值得的。',

        'story.section3_title': '三、在美国：第一次感受到真正的温柔与尊重',
        'story.section3_p1': '抵达美国后，从门诊到住院，从医生、护士到医疗翻译、志愿者，每一个人都那么体贴、温柔。',
        'story.section3_p2': '这种"细致入微"的关怀，真的能给病人和家属带来力量。',
        'story.section3_p3': '医院干净、安静，像家一样舒适；每个流程都清晰透明，没有推诿，没有混乱。',
        'story.section3_p4': '我最难忘的是我们的主治医生 Patel 医生。他每次见到我们都会微笑、拥抱，眼神里充满真诚与同情。',
        'story.section3_p5': '那一刻我明白：在美国，看病不只是"治疗疾病"，更是一次人与人之间的互相扶持与信任。',

        'story.section4_title': '四、这五年：她活得有尊严，我们活得有方向',
        'story.section4_p1': '如果留在国内，也许生存期只有 24 个月；但在美国，她又走过了 五年，并且重新拥有了生活的节奏和尊严。',
        'story.section4_p2': '这五年，她陪着孩子成长，参与康复、学习英语、做自己喜欢的事情。我们一家一起吃饭、聊天、看电影，日子重新平静而有力量。',
        'story.section4_p3': '五年中当然也有急诊、有治疗的反复、也有焦虑、害怕和流泪。',
        'story.section4_p4': '但每一次，我们都被专业的医疗团队托住。他们从不让病人和家属感到孤单。',

        'story.section5_title': '五、世界最先进的医生、药物与临床试验',
        'story.section5_p1': '我们先后前往洛杉矶的肿瘤中心、德州的 MD Anderson、波士顿的 Dana-Farber，以及 UCLA 的顶尖乳腺癌团队。',
        'story.section5_p2': '太太接受了 13 种化疗药物、4 次放疗，还参与了最新的CAR-T临床试验。',
        'story.section5_p3': '医生根据她的情况量身定制方案，不仅关注疗效，更关注生活质量。',
        'story.section5_quote': '"你是一个人，而不是一个病例编号。"',
        'story.section5_p4': '而让我真正松一口气的，是美国的医疗保险体系。很多人以为美国看病贵，但实际上——只要保险配置正确，美国看病反而比国内更省。',
        'story.section5_p5': '我当时购买了合法的、适用于外国人的商业医疗保险：',
        'story.section5_list1': '虽然保费不低，但几乎覆盖所有治疗费用',
        'story.section5_list2': '我每月只需支付固定保费 + 小额自付',
        'story.section5_list3': '她却能用上全球最新、最先进、最昂贵的药物',
        'story.section5_p6': '在国内，很多进口药都是自费；在美国，只要保险批准，几乎全部报销。',
        'story.section5_p7': '这，就是体系的力量。',

        'story.section6_title': '六、病人最担心的事情——我们都能替你解决',
        'story.section6_p1': '很多病人最担心："流程怎么走？""签证怎么办？""语言不通怎么办？""美国看病那么贵我负担得起吗？"',
        'story.section6_p2': '这些我都经历过，也都能帮你解决。我们有完整成熟的流程，可以做到：',
        'story.service1_title': '📋 签证咨询与准备',
        'story.service1_desc': '帮助准备就医邀请函、医疗材料，选择最适合的签证方式。',
        'story.service2_title': '🏥 对接美国医院与医生',
        'story.service2_desc': '直接联系美国医院，出具官方预约确认。',
        'story.service3_title': '💰 规划并合法购买美国商业医疗保险',
        'story.service3_desc': '这一步最关键，是解决"看病贵"的核心。只要咨询我，我会告诉你如何做到。我会亲自帮你办理保险，让你在美国看病没有经济压力。',
        'story.service4_title': '💵 费用透明、可控',
        'story.service4_desc': '很多患者最终的实际开销比在国内自费更低。',
        'story.service5_title': '🤝 落地后的全程陪同',
        'story.service5_desc': '接机、住宿、翻译、陪诊、复查安排，我们都能安排妥当。',
        'story.section6_p3': '你不需要害怕，也不需要自己摸索。你只需要迈出第一步，其余的我们会替你完成。',

        'story.section7_title': '七、为什么我要继续做这件事',
        'story.section7_p1': '经历过生死的人，会更懂得生命的价值。我做这件事，不是为了赚钱。',
        'story.section7_p2': '我只是觉得：我走过的路，如果能给别人带来光，就是值得的。',
        'story.section7_p3': '我相信科学，我相信体系，我相信爱。我身边有一群志愿者，他们愿意无偿帮助病人联系医院、准备材料、回答问题。',
        'story.section7_p4': '我们希望让更多家庭少走弯路，少一点无助，多一点信心。',

        'story.section8_title': '八、写在最后',
        'story.section8_p1': '五年的时间，让我们重新理解了"生命"与"希望"。太太在美国继续治疗，生活有规律、有方向、有尊严。我们全家学会了珍惜每一天的平静与陪伴。',
        'story.section8_p2': '我把这段经历写下来，是想告诉所有正在经历痛苦的家庭：',
        'story.section8_highlight': '世界上真的有希望。',
        'story.section8_p3': '如果你正在犹豫、害怕、徘徊，请相信我：这条路值得一走。',
        'story.section8_p4': '我愿意把自己的亲身经历分享给你，帮你走得更稳一些，让你少一点恐惧，多一点信心。',
        'story.signature_name': 'Glory Gao',
        'story.signature_title': '赴美医疗创始人',
        'story.signature_quote': '"把我走过的路，变成你能依靠的光。"',

        // 信件页面
        'letter.title': '给你的一封信',
        'letter.greeting': '亲爱的朋友：',
        'letter.opening1': '当你看到这封信，也许你正在经历人生的一段艰难时刻。也许你在焦虑中寻找答案，也许你正在为家人拼命寻找希望。',
        'letter.opening2': '请允许我先向你表达最真诚的问候。我懂你此刻的心情——因为我曾经站在你的位置。',
        'letter.opening3': '我是 Glory Gao，这家赴美医疗服务机构的创始人。我是一名丈夫、一个父亲，也是一个陪伴家人走过五年抗癌之路的人。',
        'letter.intro1': '正是那段经历，让我深深明白：',
        'letter.intro2': '',
        'letter.intro3': '',
        'letter.highlight1': '人在绝望中最需要的不是复杂的流程，而是一份踏实的手、真诚的心，以及可信赖的指引。',

        'letter.why_title': '我为什么愿意亲自与你联系？',
        'letter.why1': '因为我不希望你再走弯路。',
        'letter.why2': '因为我知道每个决定都关乎生命质量。',
        'letter.why3': '因为我知道，在疾病面前，"信任"比任何医疗术语都重要。',
        'letter.why4': '我走过那条路，我知道哪一步该怎么做，我知道什么时候最容易被耽误，我知道怎样把希望抓回来。',
        'letter.why5': '我愿意用我真实的经历，让你感受到：',
        'letter.why6': '我不是在"提供服务"，我是想陪你一起走过这段路。',

        'letter.trust_title': '为什么你可以信任我？',
        'letter.trust_intro': '因为我经历过你正在经历的一切：',
        'letter.trust1': '我知道绝望是什么',
        'letter.trust2': '我知道恐惧是什么',
        'letter.trust3': '我知道等待检查报告的心情是什么',
        'letter.trust4': '我知道每个家庭承受的压力',
        'letter.trust5': '我知道一个丈夫、一个母亲、一个孩子在生病时最需要什么',
        'letter.trust_because': '正因如此，我比任何人都清楚：',
        'letter.trust_emphasis': '医疗不是冷冰冰的流程，而是一种责任。',

        'letter.commitment1': '对妻子，我尽心。对家庭，我尽责。对患者，我同样会用同样的真心对待。',
        'letter.commitment2': '我愿意承担这份沉重却有意义的工作，因为这是我人生新的使命。',
        'letter.commitment3': '这让我觉得自己真实、有价值、有成就感。',
        'letter.commitment4': '这世界上也正因为这份工作"太沉重"，真正能做的人并不多。但我适合，也愿意。',

        'letter.promise_title': '我承诺：每一个咨询我都会亲自回复',
        'letter.promise1': '我们是一个非常小的团队——仅 5 名核心成员，每一位都是认真、有爱心的人。',
        'letter.promise2': '而你来到美国后，我们也会为你对接一家 美国当地的非盈利义工组织，帮助你安顿生活、陪诊、语言支持，让你真正无后顾之忧。',
        'letter.promise3': '但请理解：我能亲自服务的人数有限。',
        'letter.promise4': '所以如果你需要帮助，请尽快联系我本人。所有咨询都是免费的，只要你愿意开口，我就在这里。',

        'letter.final_quote': '选择我所承担的，承担我所选择的。',
        'letter.final1': '我会对每一位病友、每一个家庭、给出的每一句建议、每一个决定——负责到底。',
        'letter.final2': '我希望你能给我一个机会，让我用亲身经历与专业经验，带你走得更稳、活得更有质量、让你的每一天都更有尊严。',

        'letter.cta1': '如果你正在犹豫、害怕、不知从何开始——',
        'letter.cta2': '请立即联系我。我会第一时间给你最贴心、最真诚、最负责任的回应。',

        'letter.signature_name': '创始人：Glory Gao',
        'letter.signature_title': '',
        'letter.signature_message': '这是我的承诺，也是我愿意与你并肩同行的原因',

        // 页脚
        'footer.copyright': '© 2024 HealUSA. 版权所有。',
    }
};

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<'en' | 'zh'>('en');

    const t = (key: string): string => {
        return translations[language][key as keyof typeof translations['en']] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, t, setLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
}
